# Major Events in US History

## Web Scraping

#### Import Libraries

In [1]:
from bs4 import BeautifulSoup as soup
import requests

#### Request the Web Content and Save it as BeautifulSoup Object

In [2]:
URL = ['https://www.historycentral.com/Today/Index.html', 'https://www.historycentral.com/Today/21st.html']
html_content = []
for link in URL:
    r = requests.get(link)
    html_content.append(soup(r.content))

#### Use BeautifulSoup Methods to Extract The Year and Events

In [8]:
major_events = []

for page in html_content:
    table = page.find('table')
    major_events += [row.find('a').string for row in table.find_all('tr') if row.find('td') and row.find('a').string]

### Regular Expression

#### Turn Dash (-) to " " and Split the Year and Event

In [13]:
import re
events = [re.sub('-'," ",event) for event in major_events]
events = [event.split(' ', 1) for event in events]
events

[['1974', 'Soyuz Apollo'],
 ['1974', 'Ford Pardons Nixon'],
 ['1975', ' Helsinki Accords'],
 ['1975', 'NY Saved From Bankruptcy'],
 ['1976', 'Apple II Introduced'],
 ['1976', 'Carter Elected'],
 ['1977', ' USS Gives Up Panama Canal'],
 ['1979', 'Camp David Peace Accords'],
 ['1979', 'Trade Agreement'],
 ['1979', 'Three Mile Island'],
 ['1979', 'Salt II'],
 ['1980', 'Iran Seizes US Hostages'],
 ['1980', 'Soviets Invade Afghanistan'],
 ['1980', 'Reagan Election'],
 ['1981', 'Reagan fires Air Traffic Controllers'],
 ['1981Assassination', 'Attempt on Reaga'],
 ['1981', 'First Woman on Supreme Court'],
 ['1981', '$180 Billion Arms Build Up'],
 ['983', 'Bombing of US Compound in Beirut'],
 ['1984', 'Reagan Reelected'],
 ['1985', 'Reagan Tax Reform'],
 ['1986', 'Shuttle Explodes'],
 ['1986', 'US Responds to Libyan Terror'],
 ['1986', 'Iran Contra Deal Unearthed'],
 ['1988', 'INF Treaty Signed'],
 ['1988', 'George Bush Elected'],
 ['1989', 'US Seizes Panamanian Leader'],
 ['1990', 'Coalition Free Kuwait'],
 ['1992', 'Clinton Elected'],
 ['1993', 'First World Trade Center Bombing'],
 ['1993', 'Confrontation in Waco'],
 ['1993', 'PLO Israeli Agreement'],
 ['1994', 'Republicans Control Congress'],
 ['1995', 'Mexico Bailout'],
 ['1995', 'Federal Building Bombed'],
 ['1996', 'US Troops to Bosnia'],
 ['1996', 'Clinton Reelected'],
 ['1997', 'Embassy Bombed'],
 ['1998', 'President Clinton Impeached'],
 ['1999', 'Columbine School Massacre'],
 ['1999', 'US Leads Intervention in Kosovo'],
 ['2000', ' AOL Purchases Time Warner'],
 ['2000', ' USS Cole Attacked'],
 ['2000', 'Hilary Clinton Elected to Senate'],
 ['2000', 'George W Bush Elected President'],
 ['2001', ' Large Tax Cut Passed'],
 ['2001', '9/11Attack on New York and Washington'],
 ['2001', 'U.S. and Great Britain Attack Afghanistan'],
 ['2001', ' Anthrax Attacks U.S.'],
 ['2001', 'Enron Bankruptcy'],
 ['2002', 'Congress Authorizes Force Against Iraq'],
 ['2002', ' United Airlines Files For Bankruptcy'],
 ['2003', ' Shuttle Explodes on Reentry'],
 ['2003', ' U.S. Invades Iraq'],
 ['2003', ' Blackout in Northeast'],
 ['2004', 'Abu Gharib Prison Abuse'],
 ['2004', ' 9/11 Commission'],
 ['2004', ' President Bush Reelected'],
 ['2005', 'Hispanic Mayor of Los Angeles'],
 ['2005', ' Hurricane Katrina Devestates Gulf Coast'],
 ['2006', ' Hamadan vs Rumsfeld'],
 ['2006', ' Tesla Roadstar Introduced'],
 ['2007', ' iPhone Introduced'],
 ['2007', ' Virginia Tech Shooting'],
 ['2008', 'Barak Obama to be Democratic Candidate'],
 ['2008', 'Lehman Brothers Declares Bankruptcy'],
 ['2008', 'Barak Obama Wins the Presidency>'],
 ['2009', ' Barak Obama Inaugurated President'],
 ['2009', ' General Motors Declares Bankruptcy'],
 ['2009', 'President Obama Announces Troop Surge'],
 ['2010', 'Affordable Care Act Passed'],
 ['2010', 'Elana Kagan Fourth Female Justice'],
 ['2010', 'US Combat Mission Ends in Iraq'],
 ['2011', 'Osama Bin Laden Killed by US Forces'],
 ['2012', 'Hurricane Sandy'],
 ['2012', 'Obama Reelected'],
 ['2012', 'Sandy Hook School Shooting'],
 ['2013', 'Boston Marathon Bombing'],
 ['2014', 'Janet Yellen to Head Federal Reserve'],
 ['2015', 'Charleston Church Shooting'],
 ['2015', 'Supreme Court   Same Sex Marriage'],
 ['2016', 'Donald Trump Elected'],
 ['2017', ' FBI Director Fired'],
 ['2017', ' Equifax Data Breach'],
 ['2018', ' Trump Leaves Iran Nuclear Accord '],
 ['2018', 'Contentious G7 Meeting'],
 ['2018', 'US North Korean Summit '],
 ['2018', '12 Russian GRU Officers Indicted '],
 ['2018', 'Trump Putin Meet in Helesinki'],
 ['2018', 'Cohen and Manafort Guilty'],
 ['2018', 'Only 30,000 Refugees to be admitted in 2017'],
 ['2018', 'Trump Addresses UN'],
 ['2018', 'Brett Kavanaugh Confirmed to the Supreme Court'],
 ['2018', 'Massacre at Synagogue in Pittsburgh'],
 ['2018', 'Midterm Elections'],
 ['2018', 'Mattis Resigns After Trump Announcement on Syria'],
 ['2019', 'Nancy Pelosi Speaker'],
 ['2019', 'Government Shut Down Ends after 35 Days'],
 ['2019', 'Mueller Report Released on Trump and Russia'],
 ['2019', 'House Votes to Impeach President Trump'],
 ['2020', 'COVID 19 Spreads Around the World'],
 ['2020', 'Vice President Biden Becomes Presumptive Democratic Nominee'],
 ['2020', 'Space X Launches Astronauts to Space Station'],
 ['2020', 'Former Vice President Biden Elected President'],
 ['2021', 'Insurrection in Washington  The Capitol is Attacked'],
 ['2021', 'Second Impeachment Trial of Donald Trump'],
 ['2021', '2020 Census Data Released'],
 ['2021', ' Taliban Victorious in Afghanistan US Evacuates  122,000'],
 ['2022', ' Supreme Court Rules on Vaccine Mandates'],
 ['2022', ' January 6th Committee Holds Public Hearings'],
 ['2022', ' Supreme Court Overturns Roe vs Wade'],
 ['2022', ' Four Major Bills Passed by Congress'],
 ['2022', ' Congress Concludes Trump Should be Prosecuted']]

## Pandas

In [14]:
import pandas as pd

#### Make A Data frame with 'Year' and 'Event' as columns

In [32]:
df = pd.DataFrame(events, columns=['Year', 'Event'])

#### Locate row 15 and Fix the Year and Event Event = 'Assassination Attempt on Reagan' and Year = "1981"

In [33]:
df.loc[15].Year = '1981'
df.loc[15].Event = 'Assassination Attempt on Reagan'
df.head(16)

    Year                                 Event
0   1974                          Soyuz Apollo
1   1974                    Ford Pardons Nixon
2   1975                      Helsinki Accords
3   1975              NY Saved From Bankruptcy
4   1976                   Apple II Introduced
5   1976                        Carter Elected
6   1977             USS Gives Up Panama Canal
7   1979              Camp David Peace Accords
8   1979                       Trade Agreement
9   1979                     Three Mile Island
10  1979                               Salt II
11  1980               Iran Seizes US Hostages
12  1980            Soviets Invade Afghanistan
13  1980                       Reagan Election
14  1981  Reagan fires Air Traffic Controllers
15  1981       Assassination Attempt on Reagan

#### Use Replace method to turn '983' to '1983'

In [34]:
df.head(20)

    Year                                 Event
0   1974                          Soyuz Apollo
1   1974                    Ford Pardons Nixon
2   1975                      Helsinki Accords
3   1975              NY Saved From Bankruptcy
4   1976                   Apple II Introduced
5   1976                        Carter Elected
6   1977             USS Gives Up Panama Canal
7   1979              Camp David Peace Accords
8   1979                       Trade Agreement
9   1979                     Three Mile Island
10  1979                               Salt II
11  1980               Iran Seizes US Hostages
12  1980            Soviets Invade Afghanistan
13  1980                       Reagan Election
14  1981  Reagan fires Air Traffic Controllers
15  1981       Assassination Attempt on Reagan
16  1981          First Woman on Supreme Court
17  1981            $180 Billion Arms Build Up
18   983      Bombing of US Compound in Beirut
19  1984                      Reagan Reelected

In [35]:
df= df.replace('983', '1983')

#### Strip the Event Column

In [36]:
df['Event'] = df.Event.str.strip()

#### Group all the events in same year

In [41]:
df = df.groupby('Year')['Event'].apply(' / '.join).reset_index()

#### Save as CSV

In [43]:
df.to_csv('major-events-clean.csv', index=False)

#### Read CSV

In [44]:
df = pd.read_csv('major-events-clean.csv')

In [45]:
df

    Year                                              Event
0   1974                  Soyuz Apollo / Ford Pardons Nixon
1   1975        Helsinki Accords / NY Saved From Bankruptcy
2   1976               Apple II Introduced / Carter Elected
3   1977                          USS Gives Up Panama Canal
4   1979  Camp David Peace Accords / Trade Agreement / T...
5   1980  Iran Seizes US Hostages / Soviets Invade Afgha...
6   1981  Reagan fires Air Traffic Controllers / Assassi...
7   1983                   Bombing of US Compound in Beirut
8   1984                                   Reagan Reelected
9   1985                                  Reagan Tax Reform
10  1986  Shuttle Explodes / US Responds to Libyan Terro...
11  1988            INF Treaty Signed / George Bush Elected
12  1989                        US Seizes Panamanian Leader
13  1990                              Coalition Free Kuwait
14  1992                                    Clinton Elected
15  1993  First World Trade Center Bombing / Confrontati...
16  1994                       Republicans Control Congress
17  1995           Mexico Bailout / Federal Building Bombed
18  1996            US Troops to Bosnia / Clinton Reelected
19  1997                                     Embassy Bombed
20  1998                        President Clinton Impeached
21  1999  Columbine School Massacre / US Leads Intervent...
22  2000  AOL Purchases Time Warner / USS Cole Attacked ...
23  2001  Large Tax Cut Passed / 9/11Attack on New York ...
24  2002  Congress Authorizes Force Against Iraq / Unite...
25  2003  Shuttle Explodes on Reentry / U.S. Invades Ira...
26  2004  Abu Gharib Prison Abuse / 9/11 Commission / Pr...
27  2005  Hispanic Mayor of Los Angeles / Hurricane Katr...
28  2006    Hamadan vs Rumsfeld / Tesla Roadstar Introduced
29  2007         iPhone Introduced / Virginia Tech Shooting
30  2008  Barak Obama to be Democratic Candidate / Lehma...
31  2009  Barak Obama Inaugurated President / General Mo...
32  2010  Affordable Care Act Passed / Elana Kagan Fourt...
33  2011                Osama Bin Laden Killed by US Forces
34  2012  Hurricane Sandy / Obama Reelected / Sandy Hook...
35  2013                            Boston Marathon Bombing
36  2014               Janet Yellen to Head Federal Reserve
37  2015  Charleston Church Shooting / Supreme Court   S...
38  2016                               Donald Trump Elected
39  2017           FBI Director Fired / Equifax Data Breach
40  2018  Trump Leaves Iran Nuclear Accord / Contentious...
41  2019  Nancy Pelosi Speaker / Government Shut Down En...
42  2020  COVID 19 Spreads Around the World / Vice Presi...
43  2021  Insurrection in Washington  The Capitol is Att...
44  2022  Supreme Court Rules on Vaccine Mandates / Janu...